//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gizmo.Server.Bots.Telegram.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gizmo.Server.Bots.Telegram.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram bot.
        /// </summary>
        public static string TELEGRAM_BOT_MODULE_NAME {
            get {
                return ResourceManager.GetString("TELEGRAM_BOT_MODULE_NAME", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Telegram messenger integration for user verification and notifications..
        /// </summary>
        public static string TELEGRAM_BOT_MODULE_DESCRIPTION {
            get {
                return ResourceManager.GetString("TELEGRAM_BOT_MODULE_DESCRIPTION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Specify the API key for the Telegram bot..
        /// </summary>
        public static string TELEGRAM_BOT_OPTION_DESCRIPTION_API_KEY {
            get {
                return ResourceManager.GetString("TELEGRAM_BOT_OPTION_DESCRIPTION_API_KEY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message sent with the verification code. Use the {code} token to include the code..
        /// </summary>
        public static string TELEGRAM_BOT_OPTION_DESCRIPTION_CONFIRMATION_CODE_MESSAGE {
            get {
                return ResourceManager.GetString("TELEGRAM_BOT_OPTION_DESCRIPTION_CONFIRMATION_CODE_MESSAGE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Label for the button used to request the user's phone number..
        /// </summary>
        public static string TELEGRAM_BOT_OPTION_DESCRIPTION_SHARE_CONTACT_BUTTON_LABEL {
            get {
                return ResourceManager.GetString("TELEGRAM_BOT_OPTION_DESCRIPTION_SHARE_CONTACT_BUTTON_LABEL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message asking the user to share their phone number to complete verification..
        /// </summary>
        public static string TELEGRAM_BOT_OPTION_DESCRIPTION_SHARE_PHONE_MESSAGE {
            get {
                return ResourceManager.GetString("TELEGRAM_BOT_OPTION_DESCRIPTION_SHARE_PHONE_MESSAGE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Message sent to the user once verification is complete..
        /// </summary>
        public static string TELEGRAM_BOT_OPTION_DESCRIPTION_VERIFICATION_COMPLETE_MESSAGE {
            get {
                return ResourceManager.GetString("TELEGRAM_BOT_OPTION_DESCRIPTION_VERIFICATION_COMPLETE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot API key.
        /// </summary>
        public static string TELEGRAM_BOT_OPTION_NAME_API_KEY {
            get {
                return ResourceManager.GetString("TELEGRAM_BOT_OPTION_NAME_API_KEY", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmation code message.
        /// </summary>
        public static string TELEGRAM_BOT_OPTION_NAME_CONFIRMATION_CODE_MESSAGE {
            get {
                return ResourceManager.GetString("TELEGRAM_BOT_OPTION_NAME_CONFIRMATION_CODE_MESSAGE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact button label.
        /// </summary>
        public static string TELEGRAM_BOT_OPTION_NAME_SHARE_CONTACT_BUTTON_LABEL {
            get {
                return ResourceManager.GetString("TELEGRAM_BOT_OPTION_NAME_SHARE_CONTACT_BUTTON_LABEL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Share phone prompt.
        /// </summary>
        public static string TELEGRAM_BOT_OPTION_NAME_SHARE_PHONE_MESSAGE {
            get {
                return ResourceManager.GetString("TELEGRAM_BOT_OPTION_NAME_SHARE_PHONE_MESSAGE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Verification complete message.
        /// </summary>
        public static string TELEGRAM_BOT_OPTION_NAME_VERIFICATION_COMPLETE_MESSAGE {
            get {
                return ResourceManager.GetString("TELEGRAM_BOT_OPTION_NAME_VERIFICATION_COMPLETE_MESSAGE", resourceCulture);
            }
        }
    }
}
